// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using papaMiaBackend.DataAccess.Context;

#nullable disable

namespace papaMiaBackend.DataAccess.Migrations.CustomPizza
{
    [DbContext(typeof(CustomPizzaContext))]
    partial class CustomPizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomPizzaIngridient", b =>
                {
                    b.Property<int>("CustomPizzasId")
                        .HasColumnType("integer");

                    b.Property<int>("IngridientsId")
                        .HasColumnType("integer");

                    b.HasKey("CustomPizzasId", "IngridientsId");

                    b.HasIndex("IngridientsId");

                    b.ToTable("CustomPizzaIngridients", (string)null);
                });

            modelBuilder.Entity("papaMiaBackend.Domain.Entities.CustomPizza.CustomPizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CustomPizzas");
                });

            modelBuilder.Entity("papaMiaBackend.Domain.Entities.Ingridient.Ingridient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ingridients", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("CustomPizzaIngridient", b =>
                {
                    b.HasOne("papaMiaBackend.Domain.Entities.CustomPizza.CustomPizza", null)
                        .WithMany()
                        .HasForeignKey("CustomPizzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("papaMiaBackend.Domain.Entities.Ingridient.Ingridient", null)
                        .WithMany()
                        .HasForeignKey("IngridientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
