<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\papaMiaBackend.Domain\papaMiaBackend.Domain.csproj" />
    <ProjectReference Include="..\papaMiaBackend.Helpers\papaMiaBackend.Helpers.csproj" />
  </ItemGroup>

</Project>
